using System.Collections.Generic;
using UnityEngine;

/// <summary>Rig-validation animations for the avatar debug scene — each value names a state in the
/// AvatarDebugAnimator controller (see MakeHumanAnimationTestSetup). None = no controller, rest pose.</summary>
public enum DebugAnimation
{
    None,
    Idle,
    Walk,
    Run,
}

/// <summary>
/// Drop this on any GameObject in a test scene, drag an AvatarRecipeSO into `recipe`, press Play, then
/// use Build/Rebuild/Release from this component's right-click context menu (the gear icon, or
/// right-click the component header, in the Inspector) — task's own explicit tooling ask: "un
/// AvatarDebugPreview on pugui arrossegar un AvatarRecipeSO i fer Build/Rebuild/Release", so assets
/// can be iterated on without wiring a real Fight/Runner flow every time.
///
/// `additionalRecipes` spawns more avatars side by side (spaced along X) — the multi-instance check
/// that editing one avatar's body never touches another's mesh. `buildOnStart` builds automatically
/// on Play (the MakeHuman debug scene relies on it). AvatarBodyDebugPanel drives the built instances.
///
/// Requires Play Mode — AvatarFactory.CreateAsync loads real Addressables, which only resolve during
/// Play (or via an Editor-only load path this class deliberately does NOT use, to stay a thin
/// consumer of the exact same runtime path Fight/Runner use, never a parallel preview-only pipeline).
/// </summary>
public class AvatarDebugPreview : MonoBehaviour
{
    public AvatarRecipeSO recipe;

    [Tooltip("Extra recipes built next to the first one (spaced along X by `spacing`).")]
    public AvatarRecipeSO[] additionalRecipes = System.Array.Empty<AvatarRecipeSO>();

    public float spacing = 1.2f;
    public bool buildOnStart;

    [Tooltip("AvatarDebugAnimator (states Idle / Walk / Run) — see SetDebugAnimation. Generated by " +
             "Tools > MusicGame > Avatars > Setup Animation Test Clips.")]
    public RuntimeAnimatorController debugAnimatorController;

    [Tooltip("Cross-fade time when switching Idle / Walk / Run.")]
    public float animationCrossFade = 0.2f;

    [Tooltip("Imported combat/action mocap browsed by AvatarBodyDebugPanel (Tools > MusicGame > Animations > Import Rokoko Combat Packs).")]
    public CombatAnimationLibrarySO combatLibrary;

    [Tooltip("Distance between the two avatars in facing (attacker / dummy) mode.")]
    public float facingDistance = 1.1f;

    private readonly List<AvatarInstance> _instances = new();
    private readonly List<Transform> _slots = new();
    private readonly Dictionary<AvatarInstance, AvatarClipPlayer> _players = new();
    private bool _building;

    public IReadOnlyList<AvatarInstance> Instances => _instances;
    public bool IsBuilding => _building;
    public DebugAnimation CurrentAnimation { get; private set; } = DebugAnimation.None;
    public bool FacingMode { get; private set; }

    /// <summary>The clip player of `instance` while a library clip plays on it (null otherwise).</summary>
    public AvatarClipPlayer PlayerOf(AvatarInstance instance) =>
        instance != null && _players.TryGetValue(instance, out var player) && player.IsValid ? player : null;

    /// <summary>Plays an arbitrary clip (e.g. a combat library entry) on `targets` (default: every built
    /// avatar) through AvatarClipPlayer — same instances, same Animators, nothing rebuilt; body edits keep
    /// working while it plays. Replaces the Idle/Walk/Run controller on those avatars.</summary>
    public void PlayClip(AnimationClip clip, bool loop, float speed = 1f, IEnumerable<AvatarInstance> targets = null, float crossFade = 0.15f)
    {
        if (clip == null) return;
        CurrentAnimation = DebugAnimation.None;
        foreach (var instance in targets ?? _instances)
        {
            var animator = instance?.Animator;
            if (animator == null) continue;
            animator.applyRootMotion = false;
            animator.runtimeAnimatorController = null;
            if (!_players.TryGetValue(instance, out var player) || !player.IsValid)
                _players[instance] = player = new AvatarClipPlayer(animator);
            player.Speed = speed;
            player.Paused = false;
            player.Play(clip, loop, crossFade);
        }
    }

    /// <summary>Stops library clip playback (the avatars keep their last pose unless `resetPose`).</summary>
    public void StopClips(bool resetPose = false)
    {
        foreach (var (instance, player) in _players)
        {
            player.Dispose();
            if (resetPose) instance?.ResetToRestPose();
        }
        _players.Clear();
    }

    /// <summary>Facing mode: avatar 0 (attacker) and avatar 1 (dummy) face each other along X,
    /// `facingDistance` apart. Off: the normal side-by-side line-up facing +Z.</summary>
    public void SetFacingMode(bool facing)
    {
        FacingMode = facing && _slots.Count >= 2;
        for (int i = 0; i < _slots.Count; i++)
        {
            if (_slots[i] == null) continue;
            if (FacingMode && i < 2)
            {
                _slots[i].localPosition = new Vector3(i == 0 ? -facingDistance * 0.5f : facingDistance * 0.5f, 0f, 0f);
                _slots[i].localRotation = Quaternion.Euler(0f, i == 0 ? 90f : -90f, 0f);
            }
            else
            {
                _slots[i].localPosition = SlotPosition(i, _slots.Count);
                _slots[i].localRotation = Quaternion.identity;
                _slots[i].gameObject.SetActive(true);
            }
            if (FacingMode && i >= 2) _slots[i].gameObject.SetActive(false);
        }
    }

    private Vector3 SlotPosition(int i, int count) => new Vector3((i - (count - 1) * 0.5f) * spacing, 0f, 0f);

    private void Update()
    {
        foreach (var player in _players.Values) player.Tick(Time.deltaTime);
    }

    /// <summary>Plays one rig-validation animation on EVERY built avatar — same instances, same
    /// Animators (only the controller/state changes; the avatar is never rebuilt). Body edits keep
    /// working while it plays. Root motion stays off so the avatars animate in place.</summary>
    public void SetDebugAnimation(DebugAnimation animation)
    {
        if (animation != DebugAnimation.None && debugAnimatorController == null)
        {
            Debug.LogWarning("[AvatarDebugPreview] No debugAnimatorController assigned — run Tools > MusicGame > Avatars > Setup Animation Test Clips.");
            return;
        }

        StopClips(resetPose: animation == DebugAnimation.None);
        CurrentAnimation = animation;
        foreach (var instance in _instances)
        {
            var animator = instance?.Animator;
            if (animator == null) continue;
            animator.applyRootMotion = false;

            if (animation == DebugAnimation.None)
            {
                animator.runtimeAnimatorController = null;
                instance.ResetToRestPose();
                continue;
            }

            if (animator.runtimeAnimatorController != debugAnimatorController)
            {
                animator.runtimeAnimatorController = debugAnimatorController;
                animator.Play(animation.ToString(), 0, 0f);
            }
            else
            {
                animator.CrossFadeInFixedTime(animation.ToString(), animationCrossFade, 0);
            }
        }
    }

    private void Start()
    {
        if (buildOnStart) Build();
    }

    [ContextMenu("Build")]
    public void Build()
    {
        if (!Application.isPlaying)
        {
            Debug.LogWarning("[AvatarDebugPreview] Build only works in Play Mode — AvatarFactory loads real Addressables.");
            return;
        }
        if (recipe == null)
        {
            Debug.LogWarning("[AvatarDebugPreview] No AvatarRecipeSO assigned.");
            return;
        }
        if (_instances.Count > 0 || _building)
        {
            Debug.LogWarning("[AvatarDebugPreview] Already built — use Rebuild to replace it.");
            return;
        }

        _ = BuildAsync();
    }

    [ContextMenu("Rebuild")]
    public void Rebuild()
    {
        Release();
        Build();
    }

    [ContextMenu("Release")]
    public void Release()
    {
        StopClips();
        FacingMode = false;
        foreach (var instance in _instances) instance?.Dispose();
        _instances.Clear();
        foreach (var slot in _slots) if (slot != null) Destroy(slot.gameObject);
        _slots.Clear();
    }

    private async System.Threading.Tasks.Task BuildAsync()
    {
        _building = true;
        var recipes = new List<AvatarRecipeSO> { recipe };
        foreach (var extra in additionalRecipes) if (extra != null) recipes.Add(extra);

        for (int i = 0; i < recipes.Count; i++)
        {
            // Each avatar gets its own slot so they stand side by side, centred on this transform.
            var slot = new GameObject($"AvatarSlot_{i}_{recipes[i].name}").transform;
            slot.SetParent(transform, false);
            slot.localPosition = SlotPosition(i, recipes.Count);
            _slots.Add(slot);

            Debug.Log($"[AvatarDebugPreview] Building '{recipes[i].name}'...");
            var instance = await AvatarFactory.CreateAsync(recipes[i].ToRuntime(), slot);
            if (this == null) { instance?.Dispose(); return; }

            _instances.Add(instance);
            Debug.Log(instance?.Root != null
                ? $"[AvatarDebugPreview] Build complete — '{recipes[i].name}', {instance.EquippedItems.Count} item(s) equipped."
                : $"[AvatarDebugPreview] Build FAILED for '{recipes[i].name}' — see errors above.");
        }
        _building = false;
    }

    private void OnDestroy() => Release();
}
